// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueoybiagjvjahothhukc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlb3liaWFnanZqYWhvdGhodWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTA4MzQsImV4cCI6MjA2MDMyNjgzNH0.i3p9hUJlia_RVFk3uA7ZmiH4j1xeRuasXdTM9NwQmC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);